const STORAGE_KEY='verwaltung-vault-v1';let vault={accounts:[]},cryptoKey=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const enc=new TextEncoder(),dec=new TextDecoder();
const toB64=b=>btoa(String.fromCharCode(...new Uint8Array(b)));const fromB64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt){const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function save(){const stored=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');const salt=stored.salt?fromB64(stored.salt):crypto.getRandomValues(new Uint8Array(16));const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},cryptoKey,enc.encode(JSON.stringify(vault)));localStorage.setItem(STORAGE_KEY,JSON.stringify({salt:toB64(salt),iv:toB64(iv),data:toB64(data)}))}
async function unlock(password){const stored=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');const salt=stored?fromB64(stored.salt):crypto.getRandomValues(new Uint8Array(16));cryptoKey=await derive(password,salt);if(stored){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(stored.iv)},cryptoKey,fromB64(stored.data));vault=JSON.parse(dec.decode(plain))}else{vault={accounts:[]};const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},cryptoKey,enc.encode(JSON.stringify(vault)));localStorage.setItem(STORAGE_KEY,JSON.stringify({salt:toB64(salt),iv:toB64(iv),data:toB64(data)}))}}
function daysLeft(date){const today=new Date();today.setHours(0,0,0,0);return Math.ceil((new Date(date+'T00:00:00')-today)/86400000)}
function state(a){const d=daysLeft(a.expiry),r=Number(a.reminder||30);return d<0?'expired':d<=r?'soon':'active'}
const stateText={active:'Aktiv',soon:'Bald fällig',expired:'Abgelaufen'};const fmt=d=>new Intl.DateTimeFormat('de-DE').format(new Date(d+'T00:00:00'));
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function render(){const all=vault.accounts,active=all.filter(a=>state(a)==='active').length,soon=all.filter(a=>state(a)==='soon').length,expired=all.filter(a=>state(a)==='expired').length;$('#stats').innerHTML=[['Accounts',all.length,''],['Aktiv',active,''],['Bald fällig',soon,'warn'],['Abgelaufen',expired,'danger']].map(x=>`<div class="stat ${x[2]}"><p>${x[0]}</p><strong>${x[1]}</strong></div>`).join('');const urgent=[...all].sort((a,b)=>daysLeft(a.expiry)-daysLeft(b.expiry)).slice(0,8);$('#urgentList').innerHTML=urgent.length?urgent.map(a=>itemHTML(a)).join(''):'<div class="empty"><h3>Alles im Blick</h3><p>Noch keine Ablaufdaten vorhanden.</p></div>';renderTable()}
function itemHTML(a){const s=state(a),d=daysLeft(a.expiry),label=d<0?`seit ${Math.abs(d)} Tagen`:`in ${d} Tagen`;return `<div class="urgent-item"><div><strong>${esc(a.customer)}</strong><p class="sub">${esc(a.service)}</p></div><div><p>${esc(a.category)}</p></div><div><strong>${fmt(a.expiry)}</strong><p class="sub">${label}</p></div><span class="badge ${s}-badge">${stateText[s]}</span></div>`}
function renderTable(){const q=$('#search').value.toLowerCase(),filter=$('#statusFilter').value;const items=vault.accounts.filter(a=>(filter==='all'||state(a)===filter)&&[a.customer,a.service,a.username,a.url,a.category].some(v=>(v||'').toLowerCase().includes(q))).sort((a,b)=>daysLeft(a.expiry)-daysLeft(b.expiry));$('#accountRows').innerHTML=items.map(a=>{const s=state(a);return `<tr><td><strong>${esc(a.customer)}</strong><div class="sub">${esc(a.service)} · ${esc(a.category)}</div></td><td>${esc(a.username||'–')}<div class="sub">${a.url?`<a href="${safeUrl(a.url)}" target="_blank" rel="noopener">Login öffnen</a>`:'Keine URL'}</div></td><td>${fmt(a.expiry)}<div class="sub">${daysLeft(a.expiry)>=0?daysLeft(a.expiry)+' Tage verbleibend':'Abgelaufen'}</div></td><td><span class="badge ${s}-badge">${stateText[s]}</span></td><td><div class="row-actions"><button class="mini-btn" onclick="copyLogin('${a.id}')">Kopieren</button><button class="mini-btn" onclick="editAccount('${a.id}')">Bearb
eiten</button><button class="mini-btn danger-text" onclick="removeAccount('${a.id}')">Löschen</button></div></td></tr>`}).join('');$('#emptyState').classList.toggle('hidden',items.length>0)}
function esc(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}function safeUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
function switchView(view){$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#dashboardView').classList.toggle('hidden',view!=='dashboard');$('#accountsView').classList.toggle('hidden',view!=='accounts');$('#pageTitle').textContent=view==='dashboard'?'Übersicht':'Accounts';if(view==='accounts')renderTable()}
function openForm(a={}){$('#accountForm').reset();$('#accountId').value=a.id||'';$('#customer').value=a.customer||'';$('#service').value=a.service||'';$('#category').value=a.category||'Hosting';$('#expiry').value=a.expiry||'';$('#url').value=a.url||'';$('#username').value=a.username||'';$('#password').value=a.password||'';$('#reminder').value=a.reminder||'30';$('#notes').value=a.notes||'';$('#m3uOutput').value=a.m3u||'';$('#dialogTitle').textContent=a.id?'Account bearbeiten':'Neuen Account anlegen';$('#accountDialog').showModal()}
function buildM3uLink(){const base=$('#url').value.trim(),user=$('#username').value.trim(),pass=$('#password').value;if(!base||!user||!pass){showToast('Bitte URL, Benutzername und Passwort ausfüllen');return}let clean=base.replace(/\/+$/,'');const link=`${clean}/get.php?username=${encodeURIComponent(user)}&password=${encodeURIComponent(pass)}&type=m3u_plus&output=m3u8`;$('#m3uOutput').value=link;navigator.clipboard?.writeText(link).catch(()=>{});showToast('M3U-Link erstellt und kopiert')}
function parseM3uLink(){const input=window.prompt('M3U-Link einfügen:');if(!input)return;try{const u=new URL(input.trim());const user=u.searchParams.get('username'),pass=u.searchParams.get('password');if(!user||!pass){showToast('Kein gültiger M3U-Link (Benutzername/Passwort fehlen)');return}let path=u.pathname.replace(/\/get\.php$/,'').replace(/\/+$/,'');$('#url').value=`${u.origin}${path}`;$('#username').value=user;$('#password').value=pass;$('#m3uOutput').value=input.trim();showToast('Daten aus M3U-Link übernommen')}catch{showToast('Ungültiger Link')}}
window.editAccount=id=>openForm(vault.accounts.find(a=>a.id===id));window.removeAccount=async id=>{if(!confirm('Diesen Account wirklich löschen?'))return;vault.accounts=vault.accounts.filter(a=>a.id!==id);await save();render();showToast('Account gelöscht')};window.copyLogin=async id=>{const a=vault.accounts.find(x=>x.id===id);await navigator.clipboard.writeText(`${a.username||''}\n${a.password||''}`);showToast('Zugangsdaten kopiert')};
$('#unlockHint').textContent=localStorage.getItem(STORAGE_KEY)?'Gib dein Master-Passwort ein, um deine verschlüsselten Daten zu öffnen.':'Lege ein Master-Passwort mit mindestens 10 Zeichen fest. Damit werden alle Daten auf diesem Gerät verschlüsselt.';
$('#unlockForm').addEventListener('submit',async e=>{e.preventDefault();try{await unlock($('#masterPassword').value);$('#unlock').classList.add('hidden');$('#app').classList.remove('hidden');$('#masterPassword').value='';render()}catch{$('#unlockError').textContent='Falsches Master-Passwort oder beschädigte Daten.'}});
$$('.nav').forEach(n=>n.onclick=()=>switchView(n.dataset.view));$('[data-open-accounts]').onclick=()=>switchView('accounts');$('#addBtn').onclick=()=>openForm();$$('[data-close]').forEach(b=>b.onclick=()=>$('#accountDialog').close());$('#search').oninput=renderTable;$('#statusFilter').onchange=renderTable;
$('#togglePassword').onclick=()=>{const i=$('#password');i.type=i.type==='password'?'text':'password';$('#togglePassword').textContent=i.type==='password'?'Anzeigen':'Verbergen'};
$('#m3uBuildBtn').onclick=buildM3uLink;$('#m3uParseBtn').onclick=parseM3uLink;$('#m3uCopyBtn').onclick=async()=>{const v=$('#m3uOutput').value;if(!v){showToast('Kein M3U-Link vorhanden');return}await navigator.clipboard.writeText(v);showToast('M3U-Link kopiert')};
$('#accountForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#accountId').value||crypto.randomUUID();const a={id,customer:$('#customer').value.trim(),service:$('#service').value.trim(),category:$('#category').value,expiry:$('#expiry').value,url:$('#url').value.trim(),username:$('#username').value.trim(),password:$('#password').value,m3u:$('#m3uOutput').value.trim(),reminder:$('#reminder').value,notes:$('#notes').value.trim(),updatedAt:new Date().toISOString()};const idx=vault.accounts.findIndex(x=>x.id===id);idx<0?vault.accounts.push(a):vault.accounts[idx]=a;await save();$('#accountDialog').close();render();showToast('Account gespeichert')});
$('#lockBtn').onclick=()=>location.reload();$('#exportBtn').onclick=()=>{const raw=localStorage.getItem(STORAGE_KEY);const blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`verwaltung-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);showToast('Verschlüsseltes Backup exportiert')};
